export default [
  'Chat', 'Maison', 'Avion', 'Arbre', 'Montagne', 'Voiture', 'Soleil', 'Étoile', 'Plage', 'Ordinateur',
  'Livre', 'Gâteau', 'Éléphant', 'Bateau', 'Piano', 'Champignon', 'Oiseau', 'Chapeau',
  'Caméra', 'Fusée', 'Ciseaux', 'Poisson', 'Écouteurs', 'Lapin', 'Robot', 'Téléphone', 'Grenouille', 'Vélo',
  'Crayon', 'Feuille', 'Vache', 'Nuage', 'Horloge', 'Cheminée', 'Pluie', 'Guitare', 'Plante',
  'Lune', 'Échelle', 'Train', 'Épée', 'Papillon', 'Serpent', 'Planète', 'Ballon', 'Dragon', 'Radio',
  'Tasse', 'Porte', 'Télévision', 'Cerf', 'Papier', 'Géant', 'Chien', 'Poupée', 'Pont', 'Boussole',
  'Miroir', 'Souris', 'Crabe', 'Palmier', 'Parapluie', 'Château', 'Pinceau', 'Lézard', 'Fusil', 'Flamme',
  'Diamant', 'Chaussure', 'Télécommande', 'Pingouin', 'Tambour', 'Globe', 'Casque', 'Toboggan', 'Clé',
  'Bulle', 'Pizza', 'Hibou', 'Escalier', 'Cactus', 'Plongée', 'Glaçon', 'Singe',
  'Citron', 'Piscine', 'Avocat', 'Microscope', 'Cascade', 'Biberon',
  'Casquette', 'Ampoule', 'Clavier', 'Tournesol', 'Perroquet', 'Carte', 'Vinaigrette',
  'Balançoire', 'Tente', 'Harpe', 'Voile', 'Théière', 'Tornade', 'Hérisson', 'Boussole', 'Cœur',
  'Fontaine', 'Trompette', 'Sandwich', 'Bouée', 'Maïs', 'Haltère', 'Râteau', 'Portefeuille',
  'Cabane', 'Lac', 'Phare', 'Galaxie', 'Métronome', 'Grenade', 'Chariot', 'Échiquier', 'Cadenas',
  'Torche', 'Canon', 'Raisin', 'Escargot', 'Sifflet', 'Barbecue', 'Trampoline', 'Cigogne',
  'Écureuil', 'Vague', 'Masse', 'Arrosoir',
  'Pelle', 'Tambourin', 'Écrou', 'Manteau', 'Moustache', 'Cendrier',
  'Échelle', 'Cheminer', 'Hélicoptère', 'Plume', 'Marteau',
  'Microphone', 'Étagère', 'Tambourin', 'Chaussette', 'Labyrinthe', 'Fauteuil',
  'Cadenas', 'Étiquette', 'Cuirassé', 'Toupie', 'Nid', 'Râteau', 'Balance', 'Thermomètre', 'Moustache',
  'Marionnette', 'Gourde',
];
